### ISSUE TITLE
Add a contributors in the website.

### ISSUE THREAD

**Issue by chapimenge3** [CodeNight-Ethiopia/codenight-frontend#12] opened 2023-03-28 01:25 UTC
Add the Contributors of this repo in the website as an appreciation and they can also show it thier work to others by referring that dedicated page that they have contributed to this repository.

**Comment by baydisng13** [comment] 2023-04-05 21:54
This issue appears to be a duplicate of another one that has already been [reported](https://github.com/CodeNight-Ethiopia/codenight-frontend/issues/8). Thank you for your contribution

**Closed** 2023-04-05 21:55 UTC
